/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "osdconfig.h"

// autogenerated, don't edit
//

osd_params_t osd_params = {
    1,1,350,40,0,2,1,1,10,240,0,0,1,1,65,240,0,0,1,1,10,230,0,0,1,1,350,54,1,2,1,1,200,230,0,0,1,1,200,240,0,0,1,1,350,230,0,2,1,1,350,240,0,2,1,2,0,230,0,0,1,2,70,230,0,0,1,2,200,230,0,0,1,2,280,230,0,0,1,1,350,25,0,2,1,2,5,10,0,0,1,1,350,1,1,1,3,10,190,0,0,1,1,10,0,0,1,1,0,350,210,0,0,40,14,0,0,0,0,40,24,0,0,1,2,15,1,1,45,40,20,25,25,1,1,0,1,2,0,1,1,8,1200,0,0,1200,180,25,1,1,1,1,20,0,2,0,100,0,10,0,1000,1,1,305,190,0,1,1,200,220,0,0,0,100,0,0,1,2,10,100,0,1,180,133,1,0,180,133,1,0,40,0,0,10,1,133,133,1,1,65,230,0,0,0,0,350,210,0,2,0,1,4,120,1,0,0,1,2,5,25,0,0,1,1,2,5,55,0,0,0,0,7,0,0,0,350,200,0,2,1,1,0,0,150,235,0,0,5,1000,2000,0,0,0,200,200,0,0,15,15,0,0,184,240,0,0,0,0,264,240,0,0
};	
